apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: homarr
spec:
  selector:
    app: homarr
  externalTrafficPolicy: Local
  ports:
  - port: 7575
    protocol: TCP
    targetPort: 7575
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homarr
  namespace: homarr
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: home.promisedweb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homarr
            port:
              number: 7575
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  serviceName: homarr
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/wizarrrr/wizarr
          env:
            - name: homarr_port
              value: "7575"
            - name: port
              value: "7575"
            - name: TZ
              value: "America/New_York"
          ports:
            - name: homarr
              containerPort: 7575
              protocol: TCP
          volumeMounts:
            - name: homarr
              mountPath: /app/data/configs
              mountPath: /app/public/icons

  volumeClaimTemplates:
    - metadata:
        name: homarr
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 1Gi
